//
//  Airline.swift
//  mshao Greater China Region Airline List
//
//  Created by Mingfei Shao on 3/4/17.
//  Copyright © 2017 Mingfei Shao. All rights reserved.
//

import Foundation

var airlines = [
    Airline(name: "Air China",
            type: .fullservice,
            country: .CHN,
            iataCode: "CA",
            icaoCode: "CCA",
            hub: ["ZBAA", "ZUUU", "ZSSS", "ZSPD"],
            focus: ["ZGGG", "ZUCK", "ZSHC", "ZBHH", "ZBTJ", "ZUGY", "ZHHH", "ZULS"],
            founded: 1988,
            callsign: "Air China",
            fleetSize: 338,
            website: "http://www.airchina.com/",
            description: "Air China Limited is the flag carrier and one of the major airlines of the People's Republic of China, with its headquarters in Shunyi District, Beijing. Air China's flight operations are based at Beijing Capital International Airport. In 2013, the airline carried 51 million domestic and international passengers with an average load factor of 81%."),
    
    Airline(name: "China Eastern",
            type: .fullservice,
            country: .CHN,
            iataCode: "MU",
            icaoCode: "CES",
            hub: ["ZSSS", "ZSPD", "ZPPP", "ZLXY", "ZBAA"],
            focus: ["ZUUU", "ZSOF", "ZSNJ", "ZSHC", "ZSNB", "ZSWX", "ZSYN", "VHHH", "ZHHH", "ZSQD", "ZBSJ"],
            founded: 1988,
            callsign: "China Eastern",
            fleetSize: 443,
            website: "http://www.ceair.com/",
            description: "China Eastern Airlines Corporation Limited is an airline headquartered in the China Eastern Airlines Building, on the grounds of Shanghai Hongqiao International Airport in Changning District, Shanghai, China. It is a major Chinese airline operating international, domestic and regional routes. Its main hubs are at Shanghai Pudong International Airport and Shanghai Hongqiao International Airport, with secondary hubs at Beijing Capital International Airport, Kunming Changshui International Airport and Xi'an Xianyang International Airport."),
    
    Airline(name: "China Southern",
            type: .fullservice,
            country: .CHN,
            iataCode: "CZ",
            icaoCode: "CSN",
            hub: ["ZBAA", "ZUCK", "ZGGG", "ZSPD", "ZWWW"],
            focus: ["ZYCC", "ZGHA", "ZUUU", "ZYTL", "ZYHB", "ZJHK", "ZSHC", "RKSI", "ZGOW", "ZYTX", "ZGSZ", "ZHHH", "ZLXY", "ZHCC", "ZGSD"],
            founded: 1991,
            callsign: "China Southern",
            fleetSize: 621,
            website: "http://www.csair.com/",
            description: "China Southern Airlines Company Limited is an airline headquartered in Baiyun District, Guangzhou, Guangdong Province, China. It is the world's sixth-largest airline measured by passengers carried and Asia's largest airline in fleet size, revenue and passengers carried. It is the fourth-largest airline in the world in domestic passenger traffic and the sixth-largest in scheduled domestic passenger-kilometres flown. From its main hubs at Beijing Capital International Airport and Guangzhou Baiyun International Airport, the airline flies to 193 destinations using a fleet of more than 500 aircraft."),
    
    Airline(name: "Hainan Airlines",
            type: .fullservice,
            country: .CHN,
            iataCode: "HU",
            icaoCode: "CHH",
            hub: ["ZBAA", "ZJHK", "ZLXY"],
            focus: ["ZBTY", "ZWWW", "ZYTL", "ZGGG", "ZGSZ", "ZSHC"],
            founded: 1989,
            callsign: "Hainan",
            fleetSize: 171,
            website: "http://www.hnair.com/",
            description: "Hainan Airlines Co., Ltd. is an airline headquartered in Haikou, Hainan, People's Republic of China. It is the largest civilian-run air transport company and the fourth-largest airline in terms of fleet size in the People's Republic of China. It operates scheduled domestic and international services on 500 routes from Hainan and nine locations on the mainland, as well as charter services. Its main base is Haikou Meilan International Airport, with a hub at Beijing Capital International Airport and several focus cities."),
    
    Airline(name: "Shanghai Airlines",
            type: .fullservice,
            country: .CHN,
            iataCode: "FM",
            icaoCode: "CSH",
            hub: ["ZSSS", "ZSPD"],
            focus: ["N/A"],
            founded: 1985,
            callsign: "Shanghai Air",
            fleetSize: 74,
            website: "http://www.shanghai-air.com/",
            description: "Shanghai Airlines is an airline headquartered in Shanghai, China. It is a wholly owned subsidiary of China Eastern Airlines, but its operations remain separate post-merger, retaining its distinct brand and livery. Shanghai Airlines operates domestic and international services. The logo is a white crane on a red vertical tail fin. Its bases are Shanghai Pudong International Airport and Shanghai Hongqiao International Airport. The airline is an affiliate member of the SkyTeam airline alliance with its parent company China Eastern Airlines."),
    
    Airline(name: "Shandong Airlines",
            type: .fullservice,
            country: .CHN,
            iataCode: "SC",
            icaoCode: "CDG",
            hub: ["ZSJN", "ZSQD", "ZBTJ"],
            focus: ["ZBAA", "ZUCK", "ZSAM", "ZSYT"],
            founded: 1994,
            callsign: "Shandong",
            fleetSize: 76,
            website: "http://www.shandongair.com.cn/",
            description: "Shandong Airlines Co,.Ltd. is an airline based in the Shandong Airlines Center in Jinan, Shandong, China. The Chinese carrier operates mainly domestic trunk routes from Jinan, Qingdao and Yantai to major cities in China. It is owned by Air China and holds a 10 percent stake in Sichuan Airlines."),
    
    Airline(name: "Shenzhen Airlines",
            type: .fullservice,
            country: .CHN,
            iataCode: "ZH",
            icaoCode: "CSZ",
            hub: ["ZGSZ", "ZGGG", "ZYTX"],
            focus: ["ZSWX", "ZSNJ", "ZGNN", "ZLXY", "ZBAA"],
            founded: 1992,
            callsign: "Shenzhen Air",
            fleetSize: 160,
            website: "http://www.shenzhenair.com/",
            description: "Shenzhen Airlines is an airline headquartered in Shenzhen Bao'an International Airport in Bao'an District, Shenzhen, Guangdong, China.[1][2] It has been a member of Star Alliance since 2012, and is currently one of two Chinese airlines that is part of the global airline network."),
    
    Airline(name: "Air China Cargo",
            type: .cargo,
            country: .CHN,
            iataCode: "CA",
            icaoCode: "CAO",
            hub: ["ZBAA", "ZGGG", "ZSPD"],
            focus: ["N/A"],
            founded: 2003,
            callsign: "Air China Freight",
            fleetSize: 8,
            website: "http://www.airchinacargo.com/",
            description: "Air China Cargo Co., Ltd. is a cargo airline of the People's Republic of China with its headquarters in Shunyi District in Beijing. It is an all-cargo subsidiary of Air China and operates scheduled freighter services to 20 cities in 10 countries around the world. Its main base is Beijing Capital International Airport."),
    
    Airline(name: "Air Macau",
            type: .fullservice,
            country: .MAC,
            iataCode: "NX",
            icaoCode: "AMU",
            hub: ["VMMC"],
            focus: ["N/A"],
            founded: 1994,
            callsign: "Air Macau",
            fleetSize: 17,
            website: "http://www.airmacau.com.mo/",
            description: "Air Macau Company Limited is the flag carrier airline of Macau. It operates services to 23 destinations in Mainland China, Japan, South Korea, Thailand, Taiwan and Vietnam, as well as regional international services, from its hub at Macau International Airport. In 2014, Air Macau carried 2.12 million passengers with an average load factor of 68.20% and carried 15,900 tonnes of cargo and mail."),
    
    Airline(name: "XiamenAir",
            type: .fullservice,
            country: .CHN,
            iataCode: "MF",
            icaoCode: "CXA",
            hub: ["ZSAM", "ZSFZ", "ZSHC", "ZGHA"],
            focus: ["ZSCN", "ZBTJ", "ZBAA", "ZSQZ", "ZSWY", "ZHCC", "ZUCK"],
            founded: 1984,
            callsign: "Xiamen Air",
            fleetSize: 130,
            website: "http://www.xiamenair.com/",
            description: "XiamenAir is the first airline operated in the course of modern enterprise in China. Established on July 25, 1984 and based in Xiamen, Fujian Province it operates scheduled passenger flights out of Xiamen Gaoqi International Airport and, to a lesser extent, Fuzhou Changle International Airport and Hangzhou Xiaoshan International Airport. The airline is owned by China Southern Airlines (55%), Xiamen Construction and Development Group (34%), and Fujian Investment & Development Group (11%). Xiamen Airlines holds a 99.23% stake in Hebei Airlines, 60% stake in Jiangxi Airlines. By early 2014, the Airlines has set up branches in Fuzhou, Nanchang, Hangzhou, Tianjin, Changsha, and Beijing."),
    
    Airline(name: "Sichuan Airlines",
            type: .fullservice,
            country: .CHN,
            iataCode: "3U",
            icaoCode: "CSC",
            hub: ["ZUUU", "ZUCK", "ZPPP"],
            focus: ["ZBAA", "ZSHC", "ZLXY", "ZYHB", "ZJSY"],
            founded: 1986,
            callsign: "Si Chuan",
            fleetSize: 120,
            website: "http://www.scal.com.cn/",
            description: "Sichuan Airlines Co., Ltd. is a regional airline headquartered on the grounds of Chengdu Shuangliu International Airport in Chengdu, Sichuan in China, operating mainly scheduled domestic flights out of Chengdu Shuangliu Airport and Chongqing Jiangbei International Airport. The airline launched its first long-haul overseas route in June 2012 with flights from its Chengdu hub to Vancouver, Canada. Its second long-haul flight, from Chengdu to Melbourne, Australia, was launched in February 2013 with three weekly services. On October 17, 2016 the airline launched twice-a-week service from Chengdu via Hangzhou to Los Angeles (LAX)."),
    
    Airline(name: "China Southern Cargo",
            type: .cargo,
            country: .CHN,
            iataCode: "CZ",
            icaoCode: "CSN",
            hub: ["ZGGG", "ZSPD"],
            focus: ["N/A"],
            founded: 1991,
            callsign: "China Southern Cargo",
            fleetSize: 8,
            website: "http://cargo.csair.com/cn/",
            description: "China Southern Cargo is the cargo subsidiary of China Southern Airlines. The cargo airline provides services between mainland China and North America, Europe, and Australia, where destinations such as Amsterdam, Anchorage, Chicago, Frankfurt, Los Angeles, Vancouver, and Vienna are served from its main hub at Shanghai Pudong International Airport, with cargo flights to Amsterdam and Milan from Guangzhou Baiyun International Airport. The cargo subsidiary has joined the SkyTeam Cargo alliance in November 2010."),
    
    Airline(name: "China United Airlines",
            type: .lowcost,
            country: .CHN,
            iataCode: "KN",
            icaoCode: "CUA",
            hub: ["ZBNY"],
            focus: ["N/A"],
            founded: 1986,
            callsign: "Lianhang",
            fleetSize: 25,
            website: "http://www.cu-air.com/",
            description: "China United Airlines Co., Ltd. is a budget airline with its headquarters in Fengtai District, Beijing, China, operating scheduled flights and charter services in co-operation with local enterprises out of Beijing Nanyuan Airport, making it the only commercial airline using this airport. The airline previously had its headquarters in another area in Fengtai District, Beijing."),
    
    Airline(name: "China Cargo Airlines",
            type: .cargo,
            country: .CHN,
            iataCode: "CK",
            icaoCode: "CKK",
            hub: ["ZSPD"],
            focus: ["N/A"],
            founded: 1998,
            callsign: "Cargo King",
            fleetSize: 19,
            website: "http://www.ckair.com/",
            description: "China Cargo Airlines is a cargo airline with its head office on Hongqiao International Airport in Shanghai, People's Republic of China. It is China's first all-cargo airline operating dedicated freight services using China Eastern Airlines route structure. Its main base is Shanghai Hongqiao International Airport, with a hub at Shanghai Pudong International Airport."),
    
    Airline(name: "Lucky Air",
            type: .lowcost,
            country: .CHN,
            iataCode: "8L",
            icaoCode: "LKE",
            hub: ["ZPPP", "ZPLJ"],
            focus: ["ZHHH", "ZUUU"],
            founded: 2004,
            callsign: "Lucky Air",
            fleetSize: 26,
            website: "http://www.luckyair.net/",
            description: "Lucky Air is an airline based in the Xiángpéng Hángkōng Dàshà in Kunming, Yunnan, China. It operates scheduled services from Dali to Kunming and Xishuangbanna, and plans to expand to other areas of China. Its main base is Kunming Changshui International Airport. The airline is one of the four founding members of the U-FLY Alliance."),
    
    Airline(name: "West Air",
            type: .lowcost,
            country: .CHN,
            iataCode: "PN",
            icaoCode: "CHB",
            hub: ["ZUCK", "ZHCC"],
            focus: ["N/A"],
            founded: 2005,
            callsign: "West China",
            fleetSize: 23,
            website: "http://www.westair.cn/",
            description: "West Airlines Co. Ltd. operating as West Air, is a low-cost airline based in New North Zone, Chongqing, People's Republic of China, operating a scheduled passenger network to 18 domestic destinations out of Chongqing Jiangbei International Airport and one international one to Changi Airport in Singapore. The company was established in March 2006 by its parent company Hainan Airlines, with the launch of scheduled services on 14 July 2010. The airline is one of the four the founding members of the U-FLY Alliance."),
    
    Airline(name: "Hong Kong Airlines",
            type: .fullservice,
            country: .HKG,
            iataCode: "HX",
            icaoCode: "CRK",
            hub: ["VHHH"],
            focus: ["N/A"],
            founded: 2006,
            callsign: "Bauhinia",
            fleetSize: 34,
            website: "http://www.hkairlines.com/",
            description: "Hong Kong Airlines Ltd IATA: HX is a Hong Kong airline company, with its corporate headquarters in Tung Chung district and its main hub at Chek Lap Kok International Airport. It was established in 2006."),
    
    Airline(name: "HK Express",
            type: .lowcost,
            country: .HKG,
            iataCode: "UO",
            icaoCode: "HKE",
            hub: ["VHHH"],
            focus: ["N/A"],
            founded: 1997,
            callsign: "Hong Kong Shuttle",
            fleetSize: 19,
            website: "http://www.hkexpress.com/",
            description: "Hong Kong Express Airways Limited, or HK Express, is a Hong Kongese low-cost airline which provides scheduled air service to twenty-eight destinations in Asia, including China, Japan, Korea, Cambodia, Myanmar, Vietnam, U.S. Territories, Taiwan and Thailand. The airline's main hub at Hong Kong International Airport uses a fleet that consists exclusively of Airbus A320 family . The airline is one of the four founding members of the U-FLY Alliance."),
    
    Airline(name: "Cathay Pacific",
            type: .fullservice,
            country: .HKG,
            iataCode: "CX",
            icaoCode: "CPA",
            hub: ["VHHH"],
            focus: ["RCTP", "VTBS"],
            founded: 1946,
            callsign: "Cathay",
            fleetSize: 146,
            website: "http://www.cathaypacific.com/",
            description: "Cathay Pacific is the flag carrier of Hong Kong, with its head office and main hub located at Hong Kong International Airport. The airline's operations and subsidiaries have scheduled passenger and cargo services to 180 destinations in 44 countries worldwide including codeshares, and joint ventures. Served with a fleet of wide-body aircraft, consisting of Airbus A330, Airbus A340, Airbus A350, and Boeing 777 equipment. Its wholly owned subsidiary, Cathay Dragon, operates to 44 destinations in the Asia-Pacific region from its Hong Kong base. In 2010, Cathay Pacific, together with Dragonair (rebranded Cathay Dragon), carried nearly 27 million passengers and over 1.8 million tons of cargo and mail."),
    
    Airline(name: "Cathay Dragon",
            type: .fullservice,
            country: .HKG,
            iataCode: "KA",
            icaoCode: "HDA",
            hub: ["VHHH"],
            focus: ["N/A"],
            founded: 1985,
            callsign: "Dragon",
            fleetSize: 42,
            website: "http://www.dragonair.com/",
            description: "Hong Kong Dragon Airlines Ltd, operating brand as Cathay Dragon and previously as Dragonair, is a Hong Kong-based international regional airline, with its corporate headquarters, Cathay Dragon House, and main hub at Hong Kong International Airport. As of 30 October 2013, the airline operates a scheduled passenger network to 44 destinations in 13 countries and territories across Asia."),
    
    Airline(name: "Cathay Pacific Cargo",
            type: .cargo,
            country: .HKG,
            iataCode: "CX",
            icaoCode: "CPA",
            hub: ["VHHH"],
            focus: ["PANC", "KJFK", "RCTP"],
            founded: 1946,
            callsign: "Cathay",
            fleetSize: 24,
            website: "http://www.cathaypacificcargo.com/",
            description: "Cathay Pacific Cargo is a subsidiary of Cathay Pacific providing air freighter services. Cathay Pacific Cargo operates a fleet of over 20 freighters to more than 40 destinations around the world, in addition to utilising the cargo space on its passenger aircraft. The cargo subsidiary was established in 1981 with a twice-a-week Hong Kong–Frankfurt–London service operated jointly with Lufthansa. Cathay Pacific Cargo handles most of the airline's passenger cargo. Between its cargo routes and passenger routes, it serves more than 80 destinations."),
    
    Airline(name: "Air Hong Kong",
            type: .cargo,
            country: .HKG,
            iataCode: "LD",
            icaoCode: "AHK",
            hub: ["VHHH"],
            focus: ["N/A"],
            founded: 1986,
            callsign: "Air Hong Kong",
            fleetSize: 13,
            website: "http://www.airhongkong.com.hk/",
            description: "Air Hong Kong is the only all-cargo airline based in Chek Lap Kok, Hong Kong, with its main hub at Hong Kong International Airport. The airline operates an express freight network to 12 destinations in nine countries, including China, Japan, Malaysia, Philippines, Republic of China (Taiwan), Singapore, South Korea, Thailand and Vietnam. It has a fleet of Airbus A300-600F General Freighters, which the airline was the launch customer of this new variant. Its head office is located on the fourth floor of the South Tower of Cathay Pacific City."),
    
    Airline(name: "Spring Airlines",
            type: .lowcost,
            country: .CHN,
            iataCode: "9C",
            icaoCode: "CQH",
            hub: ["ZSSS", "ZSPD"],
            focus: ["/ZYTX", "ZBSJ", "RJBB"],
            founded: 2004,
            callsign: "Air Spring",
            fleetSize: 59,
            website: "http://www.ch.com/",
            description: "Spring Airlines is a low-cost carrier with its headquarters in the Homeyo Hotel in Changning District, Shanghai, China.[2][3] While the company adopted the English name \"Spring Airlines\", the Chinese name literally means \"Spring Autumn Airlines\"."),
    
    Airline(name: "China Airlines",
            type: .fullservice,
            country: .TWN,
            iataCode: "CI",
            icaoCode: "CAL",
            hub: ["RCTP", "RCKH"],
            focus: ["VHHH", "VTBS"],
            founded: 1959,
            callsign: "Dynasty",
            fleetSize: 86,
            website: "http://www.china-airlines.com/",
            description: "China Airlines (CAL) is the flag carrier and largest airline of the Republic of China (Taiwan). It is headquartered in Taiwan Taoyuan International Airport and has 12,607 regular employees. China Airlines operates over 1,400 flights weekly to 118 airports in 115 cities (including codeshare) across Asia, Europe, North America and Oceania. The cargo division operates 91 pure freighter flights weekly. The carrier was, in 2013, the 29th and 10th largest airline in the world in terms of passenger revenue per kilometer (RPK) and freight RPK, respectively."),
    
    Airline(name: "Eva Air",
            type: .fullservice,
            country: .TWN,
            iataCode: "BR",
            icaoCode: "EVA",
            hub: ["RCTP"],
            focus: ["RCKH", "VHHH", "VTBS"],
            founded: 1989,
            callsign: "Eva",
            fleetSize: 72,
            website: "http://www.evaair.com/",
            description: "EVA Air Corporation is a Taiwanese international airline based at Taiwan Taoyuan International Airport near Taipei, Taiwan, operating passenger and dedicated cargo services to over 40 international destinations in Asia, Australia, Europe, and North America. EVA Air is largely privately owned and flies a fully international route network. It is a 5-star airline, rated by Skytrax. It is the second largest Taiwanese airline. EVA Air is headquartered in Luzhu, Taoyuan City, Taiwan."),
    
    Airline(name: "Far Eastern Air Transport",
            type: .fullservice,
            country: .TWN,
            iataCode: "FE",
            icaoCode: "FEA",
            hub: ["RCSS"],
            focus: ["N/A"],
            founded: 1957,
            callsign: "Far Eastern",
            fleetSize: 7,
            website: "http://www.fat.com.tw/",
            description: "FAT Taiwan Inc., doing business as Far Eastern Air Transport (FAT), is an airline with its head office in Songshan District, Taipei, Taiwan (Republic of China)."),
    
    Airline(name: "Mandarin Airlines",
            type: .fullservice,
            country: .TWN,
            iataCode: "AE",
            icaoCode: "MDA",
            hub: ["RCMQ"],
            focus: ["RCTP", "RCKH", "RCSS"],
            founded: 1991,
            callsign: "Mandarin",
            fleetSize: 8,
            website: "http://www.mandarin-airlines.com/",
            description: "Mandarin Airlines is an airline based in Taipei, Taiwan, whose parent company is China Airlines. The Taiwanese carrier operates domestic and regional international flights, while its parent company focuses on international operations. Charter services are also operated by the company. Its other main hub is the Taichung Airport."),
    
    Airline(name: "UNI Air",
            type: .fullservice,
            country: .TWN,
            iataCode: "B7",
            icaoCode: "UIA",
            hub: ["RCTP", "RCSS"],
            focus: ["RCKH"],
            founded: 1996,
            callsign: "Glory",
            fleetSize: 17,
            website: "http://www.uniair.com.tw/",
            description: "UNI Air is an airline based in Zhongshan, Taipei, Taiwan. It is a domestic and regional subsidiary of EVA Air. It was known as Makung Airlines until 1996, when EVA Air took a majority share of the airline. In 1998, the airline merged with Great China Airlines and Taiwan Airways, which EVA Air also had interests in, to form UNI Airways (UNI Air)."),
    
    Airline(name: "Tigerair Taiwan",
            type: .lowcost,
            country: .TWN,
            iataCode: "IT",
            icaoCode: "TTW",
            hub: ["RCTP"],
            focus: ["RCKH"],
            founded: 2013,
            callsign: "Smart Cat",
            fleetSize: 10,
            website: "http://www.tigerairtw.com/",
            description: "Tigerair Taiwan is a low-cost carrier (LCC) based at Taiwan Taoyuan International Airport. The airline currently has seven aircraft and will expand its fleet to 12 aircraft by 2016. It was the first Taiwan-based LCC to start operations and currently the only one of the two LCCs in Taiwan still flying. It was formed as a joint venture between China Airlines Group and Budget Aviation Holdings."),
]

class Airline {
    enum `Type`: String {
        case fullservice = "fullservice"
        case lowcost = "lowcost"
        case cargo = "cargo"
    }
    
    enum Country: String {
        case CHN = "China"
        case HKG = "Hong Kong"
        case MAC = "Macau"
        case TWN = "Taiwan"
    }
    
    var name: String
    var type: Type
    var country: Country
    var iataCode: String
    var icaoCode: String
    var hub: [String]
    var focus: [String]
    var founded: Int
    var callsign: String
    var fleetSize: Int
    var website: String
    var description: String
    
    init(name: String, type: Type, country: Country, iataCode: String, icaoCode: String, hub: [String], focus: [String], founded: Int, callsign: String, fleetSize: Int, website: String, description: String) {
        self.name = name
        self.type = type
        self.country = country
        self.iataCode = iataCode
        self.icaoCode = icaoCode
        self.hub = hub
        self.focus = focus
        self.founded = founded
        self.callsign = callsign
        self.fleetSize = fleetSize
        self.website = website
        self.description = description
    }
    
}
